### ISSUE TITLE
Its not on the firefox extension addon page anymore!!

### ISSUE THREAD

**Issue by 641i130** [keiww/the-tab-of-words#11]
This link doesn't work!!!

[Link](https://addons.mozilla.org/en-US/firefox/addon/the-tab-of-words/?src=https://the-tab-of-words.keipixel.com/)

**Comment by wkei** [comment]
@641i130 Thank you for reminding! I already uploaded again and it's waiting for review.

**Comment by wkei** [comment]
@641i130 It's back! Please check. https://addons.mozilla.org/en-US/firefox/addon/the-tab-of-words
