### ISSUE TITLE
The extension in Chrome web store is not available

### ISSUE THREAD

**Issue by hxhc** [keiww/the-tab-of-words#15]
I find this great extension is not available in Chrome web store, but still usable in Firefox addon store. 
Is that something wrong with Chrome?

**Comment by wkei** [comment]
Sorry. I have left for a long time.

Chrome version is back https://chrome.google.com/webstore/detail/%E8%A8%80%E8%91%89-%E3%81%AE-tab/lacmiiahoideajihiclkhmdkikkbjcnb/related

And I started to work on a new version...
