### ISSUE TITLE
能不能加上罗马音？

### ISSUE THREAD

**Issue by 164851225** [keiww/the-tab-of-words#3]

**Comment by wkei** [comment]
看来是 UI 做得太克制了……仍需学习 😂

其实是有的，藏得有些深，在 「**帳**」的右下角有個 「**romaji**」的按鈕，那個就是用显示/隐藏罗马音的。

**Comment by 164851225** [comment]
找到了 _(:зゝ∠)_
支持

**Comment by 164851225** [comment]
找到了_(:зゝ∠)_
已星~
