### ISSUE TITLE
字典問題

### ISSUE THREAD

**Issue by 1a57danc3** [keiww/the-tab-of-words#5]
せっけん
economy

N5

這個有問題吧，翻成Soap （石鹸，肥皂）都可以，爲什麽是economy？字典是否出錯請核對

{"word":"せっけん","meaning":"economy","hiragana":"","romaji":"sekken","level":5},

**Comment by 1a57danc3** [comment]
https://en.wiktionary.org/wiki/%E3%81%9B%E3%81%A3%E3%81%91%E3%82%93  
同音字。。。笑死我了

**Comment by 1a57danc3** [comment]
請各位日語學習者，能寫漢字的盡量寫漢字，報導出了偏差是要負責的

**Comment by liuziangexit** [comment]
@ky0ncheng 好的，我知道了
