### ISSUE TITLE
需要 dark 暗色模式

### ISSUE THREAD

**Issue by 1a57danc3** [keiww/the-tab-of-words#6]
夜晚的白色亮度太高了，有點刺眼

**Comment by wkei** [comment]
@ky0ncheng 回复晚了不好意思。（一直在备考 N1 假期没碰过电脑（ 
说得有道理，得加上去

**Comment by 1a57danc3** [comment]
@keiww 多謝!

**Comment by wkei** [comment]
@ky0ncheng 不好意思，迟了回复，您的暗色模式已添加，请查收 )
